name: Gitbook Build & Deploy to gh-pages

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    name: Build and Deploy Gitbook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code from GitHub
        uses: actions/checkout@v2
        with: { fetch-depth: 0 }
      - name: Install
        uses: borales/actions-yarn@master
        with:
          cmd: install
      - name: Release
        uses: borales/actions-yarn@master
        with:
          cmd: build
      - name: Checkout the `gh-pages` branch into the `_gh-pages` folder
        run: git worktree add ./_gh-pages gh-pages
      - name: Copy the compiled book files to `_gh-pages`
        run: cp -R ./build/* ./_gh-pages
      - name: Commit and push the changed book files in the `gh-pages` branch
        run: |
          cd _gh-pages
          git add .
          git status
          git config --local user.name "github-actions-gitbook-bot"
          git config --local user.email "github-actions-gitbook-bot@users.noreply.github.com"
          git commit -m "Book web site deployment"
          git push
