name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy-web:
    name: Deploy Web Site
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.9.0]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          token: ${{secrets.GITHUB_TOKEN }}
      - name: Install
        uses: borales/actions-yarn@master
        with:
          cmd: install
      - name: Build
        uses: borales/actions-yarn@master
        with:
          cmd: build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN  }}
          publish_dir: ./_book
          user_name: jerrylib
          user_email: js_bin@163.com
          publish_branch: gh-pages
